version: "3"
services:
  cloudflared:
    image: crazymax/cloudflared:2021.11.0
    restart: unless-stopped
    environment:
      TZ: 'America/New_York'
      TUNNEL_DNS_PORT: '5053'
      TUNNEL_DNS_ADDRESS: '0.0.0.0'
      TUNNEL_DNS_UPSTREAM: 'https://1.1.1.1/dns-query,https://1.0.0.1/dns-query,https://dns.quad9.net/dns-query,https://dns9.quad9.net/dns-query'
    ports:
      - 5053:5053/udp
      - 5053:5053/tcp
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  pihole:
    container_name: pihole
    image: pihole/pihole:2021.12.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5550:80/tcp"
    environment:
      TZ: 'America/New_York'
      PIHOLE_DNS_: 10.5.0.5#5053 # Use cloudflared as upstream DNS server
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    depends_on:
      - cloudflared
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
